SELECT DISTINCT 
	DHCPServer0 AS DHCP_Server, 
	COUNT(DISTINCT ResourceID) AS Clients 
FROM 
	dbo.v_GS_NETWORK_ADAPTER_CONFIGURATION 
WHERE 
	DHCPServer0 IS NOT NULL AND LTRIM(DHCPServer0)<>'' 
GROUP BY DHCPServer0